name = "fluid-bundle"
main = "src/index.js"
compatibility_date = "2024-07-23"

[assets]
directory = "./public"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true


[vars]
MAILCHIMP_AUDIENCE_ID = "5c08b07f08"
DC_API_ADDRESS = ""
CCBCHIMP_API_ADDRESS = ""
CB_API_ADDRESS = ""
BASE_URL = ""
STRIPE_CUSTOMER_PORTAL = ""
GTAG_ID = ""
INTERCOM_APP_ID = ""

# Production environment
[env.production.vars]
MAILCHIMP_AUDIENCE_ID = "5c08b07f08"
DC_API_ADDRESS = "https://my.display.church"
CCBCHIMP_API_ADDRESS = "https://sync.ccbchimp.com"
CB_API_ADDRESS = "https://my.bee.church"
BASE_URL = "https://fmbundle.com/"
STRIPE_CUSTOMER_PORTAL = "https://billing.stripe.com/p/login/eVq7sLddWfPc3k113y5ZC00"
GTAG_ID = "G-W1V9XB8245"
INTERCOM_APP_ID = "rgbdh5ho"

# Staging environment
[env.stage.vars]
MAILCHIMP_AUDIENCE_ID = "5c08b07f08"
DC_API_ADDRESS = "https://dev.display.church"
CCBCHIMP_API_ADDRESS = "https://staging.ccbchimp.com"
CB_API_ADDRESS = "https://dev.bee.church"
BASE_URL = "https://staging.fmbundle.com/"
STRIPE_CUSTOMER_PORTAL = "https://billing.stripe.com/p/login/test_00wbJ038KdOqbDP9fa4gg00"
GTAG_ID = "G-PEPQKLS2YX"
INTERCOM_APP_ID = "gr88fb4u"
